name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install

      - name: Test application
        run: yarn test

      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@main
        with:
          app_name: Tapp
          token: ${{ secrets.dop_v1_b75d4fdd245da63adfb985592aec9cce822f376d09826728d52a4d15d5448ede }}
